### ISSUE TITLE
Two emails instead of one

### ISSUE THREAD

**Issue by petros** [gjtorikian/past.codes#2]
This is so good!! Thanks so much for implementing it @gjtorikian.

I received my first email, but twice instead of once. Was this a one off problem, or is there a bug?

**Comment by gjtorikian** [comment]
D'oh! It might've been because I was messing around with some DNS settings on Mailgun. Can you let me know if that happens again next week?

I'm glad you enjoy it!

**Comment by petros** [comment]
👍 great! I will report back here next week and close the issue if it doesn't happen again 😄.

**Comment by petros** [comment]
Looks like I only got one email this time 🎉

**Comment by gjtorikian** [comment]
Yay! 

For what it's worth I figured out the issue from last week but waited for the verification. There was a bug in the email delivery, which caused the app to keep retrying stuck jobs in the queue. I fixed the bug, and manually resent new emails; but what I didn't realize was that the failed items in the job queue would get reprocessed, hence the two emails.
